services:
  db:
    image: postgres:15-alpine
    container_name: shapeapp_db
    environment:
      POSTGRES_USER: shapeapp_user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: shapeapp
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build:
      # context: tells Docker "look for source files in the project root"
      context: .
      # dockerfile: tells Docker "use the Dockerfile at this specific path"
      dockerfile: ./Docker/node/Dockerfile
    depends_on:
      - db
    environment:
      # CORRECT DATABASE_URL: Use the service name 'db', not 'localhost'
      DATABASE_URL: "postgres://shapeapp_user:password123@db:5432/shapeapp"

      # Environment variables for better-auth
      # Use AUTH_URL as the standard. NO trailing slash.
      AUTH_URL: "http://10.0.2.2:3000"
      AUTH_SECRET: "jXbEAW3wMq4V3VMMZIyc2DAF33loaqAN" # Use your secret
      AUTH_TRUST_HOST: "true" # Must be a string "true" for local dev

      # Other variables
      PORT: "3000"
      NODE_ENV: "development"
    volumes:
      # 1) mount your entire project
      - ./:/app
      # 2) keep the container’s node_modules intact
      # - /app/node_modules
    ports:
      - "3000:3000"
    command: npm run dev

  n8n:
    image: n8nio/n8n:latest
    build:
      context: .
      dockerfile: ./Docker/n8n/Dockerfile
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    depends_on:
      - n8n_db
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=n8n_db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n_user
      - DB_POSTGRESDB_PASSWORD=n8n_pass
      - NODE_FUNCTION_ALLOW_EXTERNAL=sharp
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=secret
      - GENERIC_TIMEZONE=Europe/Sarajevo
      - NODE_ENV=development
    volumes:
      - n8n-data:/home/node/.n8n
    networks:
      - backend_network

  n8n_db:                                 
    image: postgres:15-alpine             
    container_name: n8n_db
    environment:
      POSTGRES_USER: n8n_user
      POSTGRES_PASSWORD: n8n_pass
      POSTGRES_DB: n8n                    
    volumes:
      - n8n_pgdata:/var/lib/postgresql/data
    networks:
      - backend_network
volumes:
  pgdata:
  n8n-data:
  n8n_pgdata:

networks:
  backend_network:
    driver: bridge